clex: Fix macOS build with system Flex
This fixes the error:

  defs.h:22:12: error: redeclaration of 'yyleng' with a different
                type: 'int' vs 'yy_size_t' (aka 'unsigned long')
   22 | extern int yyleng;
      |            ^
  strlex.c:271:11: note: previous definition is here
  271 | yy_size_t yyleng;

The system-provided version of Flex defines yyleng differently than on
majority of other platforms, using yy_size_t == size_t instead of int.
To avoid the compilation error in the particular environment, this
commit overrides the type to unconditionally be "int" (even if size_t
might in theory be a better choice for huge files).